### ISSUE TITLE
Could not import 'waves.wcore.adaptors.shell.SshShellAdaptor' for WAVES settings 'AttributeError'

### ISSUE THREAD

**Issue by tiehan** [lirmm/waves-core#25]
(venv) [sam@c02 waves]$ ./manage.py check
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/mnt/nfs/data/user/sam/project/waves/venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/mnt/nfs/data/user/sam/project/waves/waves/wcore/apps.py", line 57, in check_waves_config
    elif len(waves_settings.ADAPTORS_CLASSES) == 0:
  File "/mnt/nfs/data/user/sam/project/waves/waves/wcore/settings.py", line 129, in __getattr__
    val = perform_import(val, attr)
  File "/mnt/nfs/data/user/sam/project/waves/waves/wcore/settings.py", line 34, in perform_import
    return [import_from_string(item) for item in val]
  File "/mnt/nfs/data/user/sam/project/waves/waves/wcore/settings.py", line 49, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'waves.wcore.adaptors.shell.SshShellAdaptor' for WAVES settings 'AttributeError': 'module' object has no attribute 'Configurable'.

**Comment by tiehan** [comment]
because radical.utils now is  0.60.1,we can low radical.utils version

pip install radical.utils==0.50.1

**Comment by marcoooo** [comment]
Is this problem still occuring with last release (1.6.5) ?

**Comment by marcoooo** [comment]
Seems not to be the case. I close the ticket then.
